"""Central registry of machine-readable error codes.

Codes follow the convention ``AF_<DOMAIN>_<REASON>`` and are stable API
contract values. Middleware maps raised exceptions onto these codes.
"""

# Generic
ERR_INTERNAL = "AF_INTERNAL_ERROR"
ERR_UNKNOWN = "AF_UNKNOWN"
ERR_NOT_IMPLEMENTED = "AF_NOT_IMPLEMENTED"
ERR_BAD_GATEWAY = "AF_BAD_GATEWAY"
ERR_SERVICE_UNAVAILABLE = "AF_SERVICE_UNAVAILABLE"
ERR_GATEWAY_TIMEOUT = "AF_GATEWAY_TIMEOUT"

# Validation
ERR_VALIDATION = "AF_VALIDATION_ERROR"
ERR_VALIDATION_SCHEMA = "AF_VALIDATION_SCHEMA"
ERR_VALIDATION_TYPE = "AF_VALIDATION_TYPE"
ERR_VALIDATION_CONSTRAINT = "AF_VALIDATION_CONSTRAINT"

# Authentication / authorization
ERR_AUTHENTICATION = "AF_AUTHENTICATION_ERROR"
ERR_AUTHENTICATION_REQUIRED = "AF_AUTH_REQUIRED"
ERR_AUTHENTICATION_INVALID = "AF_AUTH_INVALID"
ERR_AUTHENTICATION_EXPIRED = "AF_AUTH_EXPIRED"
ERR_AUTHENTICATION_REVOKED = "AF_AUTH_REVOKED"
ERR_AUTHENTICATION_BAD_CREDENTIALS = "AF_AUTH_BAD_CREDENTIALS"
ERR_AUTHORIZATION = "AF_AUTHORIZATION_ERROR"
ERR_FORBIDDEN = "AF_FORBIDDEN"
ERR_INSUFFICIENT_SCOPE = "AF_INSUFFICIENT_SCOPE"
ERR_INSUFFICIENT_PERMISSION = "AF_INSUFFICIENT_PERMISSION"
ERR_INVALID_TOKEN = "AF_INVALID_TOKEN"
ERR_TOKEN_EXPIRED = "AF_TOKEN_EXPIRED"

# NotFound / conflicts
ERR_NOT_FOUND = "AF_NOT_FOUND"
ERR_CONFLICT = "AF_CONFLICT"
ERR_ALREADY_EXISTS = "AF_ALREADY_EXISTS"
ERR_DUPLICATE_ENTRY = "AF_DUPLICATE_ENTRY"

# Rate limiting
ERR_RATE_LIMITED = "AF_RATE_LIMITED"
ERR_TOO_MANY_REQUESTS = "AF_TOO_MANY_REQUESTS"
ERR_QUOTA_EXCEEDED = "AF_QUOTA_EXCEEDED"

# Providers / LLM
ERR_PROVIDER = "AF_PROVIDER_ERROR"
ERR_PROVIDER_TIMEOUT = "AF_PROVIDER_TIMEOUT"
ERR_PROVIDER_UNAVAILABLE = "AF_PROVIDER_UNAVAILABLE"
ERR_PROVIDER_AUTH = "AF_PROVIDER_AUTH"
ERR_PROVIDER_QUOTA = "AF_PROVIDER_QUOTA"
ERR_LLM_CONTEXT_OVERFLOW = "AF_LLM_CONTEXT_OVERFLOW"
ERR_LLM_RATE_LIMIT = "AF_LLM_RATE_LIMIT"
ERR_AI_SERVICE = "AF_AI_SERVICE_ERROR"

# Workflows / executions
ERR_WORKFLOW = "AF_WORKFLOW_ERROR"
ERR_WORKFLOW_INVALID = "AF_WORKFLOW_INVALID"
ERR_WORKFLOW_CYCLE = "AF_WORKFLOW_CYCLE"
ERR_WORKFLOW_UNDEFINED_STEP = "AF_WORKFLOW_UNDEFINED_STEP"
ERR_EXECUTION = "AF_EXECUTION_ERROR"
ERR_EXECUTION_TIMEOUT = "AF_EXECUTION_TIMEOUT"
ERR_EXECUTION_CANCELLED = "AF_EXECUTION_CANCELLED"
ERR_EXECUTION_FAILED = "AF_EXECUTION_FAILED"

# Storage / cache / retry
ERR_STORAGE = "AF_STORAGE_ERROR"
ERR_STORAGE_UPLOAD = "AF_STORAGE_UPLOAD"
ERR_STORAGE_DOWNLOAD = "AF_STORAGE_DOWNLOAD"
ERR_STORAGE_NOT_FOUND = "AF_STORAGE_NOT_FOUND"
ERR_CACHE = "AF_CACHE_ERROR"
ERR_CACHE_CONNECTION = "AF_CACHE_CONNECTION"
ERR_RETRY_EXHAUSTED = "AF_RETRY_EXHAUSTED"
ERR_TIMEOUT = "AF_TIMEOUT"
ERR_CIRCUIT_OPEN = "AF_CIRCUIT_OPEN"

# Configuration
ERR_CONFIGURATION = "AF_CONFIGURATION_ERROR"
ERR_CONFIGURATION_MISSING = "AF_CONFIGURATION_MISSING"
ERR_CONFIGURATION_INVALID = "AF_CONFIGURATION_INVALID"

# Versioning
ERR_VERSION_INCOMPATIBLE = "AF_VERSION_INCOMPATIBLE"
ERR_VERSION_PARSE = "AF_VERSION_PARSE"

# Events / messaging
ERR_EVENT = "AF_EVENT_ERROR"
ERR_EVENT_PUBLISH = "AF_EVENT_PUBLISH"
ERR_EVENT_NOT_HANDLED = "AF_EVENT_NOT_HANDLED"
