"""Timeout constants (seconds) shared across the platform."""

# General
DEFAULT_TIMEOUT_SECONDS = 30
SHORT_TIMEOUT_SECONDS = 5
MEDIUM_TIMEOUT_SECONDS = 30
LONG_TIMEOUT_SECONDS = 120

# HTTP / external services
HTTP_CONNECT_TIMEOUT_SECONDS = 10
HTTP_READ_TIMEOUT_SECONDS = 30
HTTP_WRITE_TIMEOUT_SECONDS = 30
HTTP_POOL_TIMEOUT_SECONDS = 10

# LLM providers
LLM_REQUEST_TIMEOUT_SECONDS = 120
LLM_CONNECT_TIMEOUT_SECONDS = 15
EMBEDDING_REQUEST_TIMEOUT_SECONDS = 60

# Redis
REDIS_SOCKET_TIMEOUT_SECONDS = 5
REDIS_SOCKET_CONNECT_TIMEOUT_SECONDS = 5
REDIS_LOCK_TIMEOUT_SECONDS = 30
REDIS_LOCK_WAIT_TIMEOUT_SECONDS = 10

# Database
DB_QUERY_TIMEOUT_SECONDS = 30
DB_CONNECT_TIMEOUT_SECONDS = 10

# Cache
CACHE_OPERATION_TIMEOUT_SECONDS = 3

# Jobs / workflows
JOB_DEFAULT_TIMEOUT_SECONDS = 600
WORKFLOW_DEFAULT_TIMEOUT_SECONDS = 900

# Background tasks
TASK_SHUTDOWN_GRACE_SECONDS = 30
EVENT_HANDLER_TIMEOUT_SECONDS = 30

# Retry
RETRY_DEFAULT_WAIT_SECONDS = 1.0
RETRY_ASYNC_DEFAULT_WAIT_SECONDS = 1.0
RETRY_SYNC_DEFAULT_WAIT_SECONDS = 1.0

# SSE
SSE_KEEPALIVE_SECONDS = 15

# Circuit breaker
CIRCUIT_BREAKER_RESET_SECONDS = 30
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_SUCCESS_THRESHOLD = 3
